# Integrated Transport and Health Impacts Model

## R Package _ITHIM_
<!-- This document will eventually serve as a compendium to the R package
_ITHIM_.  It will describe how to use the package to implement the
ITHIM model, as well as a detailed description of the model itself.

As a working document it will serve as a place for SGY to post
results, questions, interpreations, notes, etc.-->

```{r libs, eval = TRUE, echo = TRUE, results = "hide", warning = FALSE, error = FALSE, message = FALSE}
rm(list=ls())
library("devtools")
#install_github("syounkin/ITHIM", ref="cambridge")
install("~/ITHIM/")
document("~/ITHIM/")
install("~/ITHIM/")
library("ITHIM")
```

```{r misc, message = FALSE, eval = TRUE, warning = FALSE, error = TRUE, echo = FALSE}
fig.width <- 6 # inches
phi <- (1+sqrt(5))/2 # the golden ratio ;)
```

```{r roadInjuries, message = FALSE, eval = TRUE, warning = FALSE, error = TRUE, echo = TRUE}
scenario <- readRDS(file = "~/Downloads/distByRoadTypeScenario4.rds")
base <- readRDS(file = "~/Downloads/distByRoadTypeBaseline.rds")

ITHIM <- createITHIM()
ITHIM.baseline <- update(ITHIM, list(distRoadType = base))
ITHIM.scenario <- update(ITHIM, list(distRoadType = scenario))
ITHIM.scenario <- updateRoadInjuries(ITHIM.baseline, ITHIM.scenario)
```


```{r roadInjuries9, message = FALSE, eval = TRUE, warning = FALSE, error = TRUE, echo = TRUE}
ITHIM.baseline <- update(ITHIM.baseline, list(GBD = readGBD(file = "gbdEngland.csv")))
ITHIM.scenario <- update(ITHIM.scenario, list(GBD = readGBD(file = "gbdEngland.csv")))
```

```{r roadInjuries3, message = FALSE, eval = TRUE, warning = FALSE, error = TRUE, echo = TRUE}
RIburden <- computeRoadInjuryBurden(ITHIM.baseline, ITHIM.scenario)
deltaDeaths <- sum(subset(RIburden, burden == "dproj")$delta)
```

```{r roadInjuries4, message = FALSE, , dev=c('png'), eval = TRUE, warning = FALSE, error = TRUE, echo = TRUE}

deltaDeathsVec <- c()

for( sin in sinVec <- seq(0,1,length.out = 25) ){
    ITHIM.baseline <- update(ITHIM.baseline, list(safetyInNumbers = sin*matrix(1,nrow = 8, ncol = 2)))
    ITHIM.scenario <- updateRoadInjuries(ITHIM.baseline, ITHIM.scenario)
    RIburden <- computeRoadInjuryBurden(ITHIM.baseline, ITHIM.scenario)
    deltaDeaths <- sum(subset(RIburden, burden == "dproj")$delta)
    deltaDeathsVec <- c(deltaDeathsVec, deltaDeaths)
}

plot(sinVec, deltaDeathsVec, type = "p", pch = 20)

```
```{r roadInjuries5, message = FALSE, , dev=c('png'), eval = FALSE, warning = FALSE, error = TRUE, echo = FALSE}
    ITHIM.baseline <- update(ITHIM.baseline, list(safetyInNumbers = 0.5*matrix(1,nrow = 8, ncol = 2)))
deltaDeathsVec <- c()
for( underReporting in underReportingVec <- runif(10,0,1) ){
    cat(underReporting)
    ITHIM.baseline <- update(ITHIM.baseline, list(roadInjuries = lapply(getRoadInjuries(ITHIM.baseline), function(x) x/underReporting)))
    ITHIM.scenario <- updateRoadInjuries(ITHIM.baseline, ITHIM.scenario)
    RIburden <- computeRoadInjuryBurden(ITHIM.baseline, ITHIM.scenario)
    deltaDeaths <- sum(subset(RIburden, burden == "dproj")$delta)
    deltaDeathsVec <- c(deltaDeathsVec, deltaDeaths)
}
plot(underReportingVec, deltaDeathsVec, type = "p", pch = 20)
```

```{r roadInjuries6, message = FALSE, , dev=c('png'), eval = TRUE, warning = FALSE, error = TRUE, echo = TRUE}

for(i in 1:10){

    simRI <- lapply(getRoadInjuries(ITHIM.baseline), function(x){
      lambda <- c(as.matrix(x))
      simCount <- matrix(mapply(function(y){rpois(1,y)},y=lambda), nrow = nrow(x), ncol = ncol(x))
      dimnames(simCount) <- dimnames(x)
      simCount
    })

ITHIM.baseline.sim <- update(ITHIM.baseline, list(roadInjuries = simRI))
    ITHIM.scenario.sim <- updateRoadInjuries(ITHIM.baseline.sim, ITHIM.scenario)
    RIburden <- computeRoadInjuryBurden(ITHIM.baseline.sim, ITHIM.scenario.sim)
    deltaDeaths <- sum(subset(RIburden, burden == "dproj")$delta)
cat(c(deltaDeaths, "\n"))

}

```
