# Integrated Transport and Health Impacts Model

## R Package _ITHIM_

```{r libs, eval = TRUE, echo = FALSE, results = "hide", warning = FALSE, error = FALSE, message = FALSE}
options(repos='http://cran.rstudio.com/')
#install.packages(c("ggplot2","dplyr","openssl","httr", "git2r", "devtools", "roxygen2"))
library("ggplot2")
library("devtools")
library("reshape2")
library("plyr")
library("dplyr")
```

```{r loadITHIM, message = FALSE, eval = TRUE, warning = FALSE, error = TRUE, echo = FALSE}
document("~/ITHIM/")
install("~/ITHIM/")
#install_github("syounkin/ITHIM", ref="devel")
install_github("smbache/magrittr", ref="master")

library("magrittr")
library("ITHIM")

fig.width <- 6 # inches
phi <- (1+sqrt(5))/2 # the golden ratio ;)
```

```{r loadNHTS, eval = TRUE}
NHTS <- readRDS(file = "~/GHI/R/data/NHTS.rds")
```

#### Compute National Metro Average

```{r natl, eval = TRUE, echo = FALSE, warning = FALSE}
listOfLists <- lapply(split(NHTS, NHTS$SEX),function(x) split(x, x$AGE))
counts <- lapply(listOfLists, function(x) lapply(x, countPeople))
walkLength <- lapply(listOfLists, function(x) lapply( x, tripTime, mode = "walk"))
cycleLength <- lapply(listOfLists, function(x) lapply( x, tripTime, mode = "cycle"))

countMatrix <- reformatData(counts)
walkMatrix <- reformatData(walkLength)
cycleMatrix <- reformatData(cycleLength)

meanWalkList <- walkMatrix/countMatrix*7
meanCycleList <- cycleMatrix/countMatrix*7

RwtList <- ifelse(meanWalkList == 0, 1e-4, meanWalkList)
RctList <- ifelse(meanCycleList == 0, 1e-4, meanCycleList)

RwtNational <- RwtList/RwtList[3,2]
RctNational <- RctList/RctList[3,2]
muwtNational <- meanWalkList[3,2]
muctNational <- meanCycleList[3,2]

rm("listOfLists","counts","walkLength","cycleLength","countMatrix","walkMatrix","cycleMatrix","meanWalkList","meanCycleList","RwtList","RctList","muwtList","muctList")
```

#### Compute Mean Trip Lengths

```{r count, eval = TRUE, echo = FALSE}
listOfLists <- lapply(split(NHTS, NHTS$MSA_ID),function(x) lapply(split(x, x$SEX), function(x) split(x, x$AGE)))
#listOfLists <- lapply(split(NHTS, NHTS$HHSTATE),function(x) lapply(split(x, x$SEX), function(x) split(x, x$AGE)))
counts <- lapply(listOfLists, function(x) lapply(x, function(x) lapply(x, countPeople)))
walkLength <- lapply(listOfLists, function(x) lapply(x, function(x) lapply( x, tripTime, mode = "walk")))
cycleLength <- lapply(listOfLists, function(x) lapply(x, function(x) lapply( x, tripTime, mode = "cycle")))
countMatrix <- lapply(counts, reformatData)
walkMatrix <- lapply(walkLength, reformatData)
cycleMatrix <- lapply(cycleLength, reformatData)
meanWalkList <- mapply(walkMatrix,   countMatrix, FUN = function(x,y) ifelse(y == 0, 0, x/y*7), SIMPLIFY = FALSE)
meanCycleList <- mapply(cycleMatrix, countMatrix, FUN = function(x,y) ifelse(y == 0, 0, x/y*7), SIMPLIFY = FALSE)

zeroReferentCase <- function(x){
  if(x[3,2]==0){
    return(matrix(1e-3,nrow=nrow(x),ncol=ncol(x), dimnames = dimnames(x)))
  }else{
    return(ifelse(x==0, 1e-3, x/x[3,2]))
  }
}

RwtList <- lapply( meanWalkList, zeroReferentCase)
RctList <- lapply( meanCycleList, zeroReferentCase)
muwtList <- lapply( meanWalkList, function(x) ifelse(x[3,2]==0,1e-3, x[3,2]))
muctList <- lapply( meanCycleList, function(x) ifelse(x[3,2]==0,1e-3, x[3,2]))
```

```{r sampleSize, eval = TRUE, dev=c('pdf', 'png'), fig.width = 3*fig.width, fig.asp = 1/phi, echo = TRUE, warning = FALSE}
foo <- lapply( countMatrix, function(x) c(x) )
foo <- melt(foo)
names(foo) <- c("sampleSize", "state")
p <- ggplot(foo, aes( x = state, y = sampleSize))
p + geom_bar(stat = "identity") + labs(y = "Sample Size (Referent Group)", x = "State") + theme_bw()
```

## Non-Travel METs

```{r newMETs, echo = TRUE, eval = TRUE, echo = FALSE}
newMETsFile <- 'https://raw.githubusercontent.com/vargovargo/ACS_ITHIM/master/ATUS_to_METS_key.csv'

#newMETsFile <- system.file(newMETsFile, package="ITHIM")

newMETs <- read.csv(file = newMETsFile, stringsAsFactors = FALSE, colClasses = c("character","character","character","character","numeric","character","character","character"))
dataColumns <- c(1,5)
D <- newMETs[,dataColumns]
metaData <- newMETs[,-dataColumns]
newMETs <- list(Data = D, metaData = metaData)
activityCode <- ifelse(nchar(newMETs$Data$X6.digit.activity.code)==5,paste0("t0",newMETs$Data$X6.digit.activity.code),paste0("t",newMETs$Data$X6.digit.activity.code))

rownames(newMETs$Data) <- activityCode
rownames(newMETs$metaData) <- activityCode

newMETs$metaData <- within(newMETs$metaData, {
  Travel.related..Y.N. <- as.factor(Travel.related..Y.N.)
})

metKey <- newMETs$Data$AinsworthMETS
names(metKey) <- activityCode


```

```{r readnewMETs, echo = TRUE, eval = TRUE, echo = FALSE}
cpsFile <- "~/GHI/data/ATUS/atuscps_2015.dat"
cps <- read.table(cpsFile, header=T, skip=0, sep="," )
cps <- within(cps, {
    TUCASEID <- as.character(TUCASEID)
    TULINENO <- as.character(TULINENO)
    GEREG <- as.factor(GEREG)
    })
cps <- subset(cps, TULINENO == "1")

summaryFile <- "~/GHI/data/ATUS/atussum_2015.dat"
summary <- read.table(summaryFile, header=T, skip=0, sep=",")
metaDataColumns <- 1:24
summaryList <- list(Data = summary[,-metaDataColumns], metaData = summary[,metaDataColumns])

summaryList$metaData <- within(summaryList$metaData,{
    TESEX <- as.factor(ifelse(TESEX == 1, "male", ifelse(TESEX == 2, "female",NA)))
    AGECAT <- ifelse(TEAGE <5, "00-04",
                     ifelse(TEAGE > 4 & TEAGE < 15, "05-14",
                     ifelse(TEAGE > 14 & TEAGE < 30, "15-29",
                     ifelse(TEAGE > 29 & TEAGE < 45, "30-44",
                     ifelse(TEAGE > 44 & TEAGE < 60, "45-59",
                     ifelse(TEAGE > 59 & TEAGE < 70, "60-69",
                     ifelse(TEAGE > 69 & TEAGE < 80, "70-79", "80+"
                            )))))))})


```

We shift the MET estimates by the minimum value so that the new minimum MET estimate is zero.

```{r metKey, echo = TRUE, eval = TRUE, echo = FALSE}
allActivities <- colnames(summaryList$Data)
nonTravelActivities <- rownames(newMETs$metaData)[which(newMETs$metaData$Travel.related..Y.N. == "N")]
nonTravelActivities <- nonTravelActivities[which(nonTravelActivities %in% allActivities)]

activities <- nonTravelActivities

metKeyVector <- (metKey[activities] - min(metKey, na.rm = TRUE))/60*7
names(metKeyVector) <- activities
metKeyMatrix <- matrix(metKeyVector, nrow = nrow(summaryList$Data), ncol = length(metKeyVector), byrow = TRUE)
dimnames(metKeyMatrix) <- list( NULL, activities)


METs <- data.frame(METs = rowSums(summaryList$Data[,activities] * metKeyMatrix[,activities], na.rm = TRUE), AGE = summaryList$metaData$TEAGE, SEX = summaryList$metaData$TESEX, AGECAT = summaryList$metaData$AGECAT, row.names = summaryList$metaData$TUCASEID )

D <- merge(cps, METs, by.y = "row.names", by.x = "TUCASEID")
ggplot(D, aes(x = METs, ..density.., colour = AGECAT)) + geom_freqpoly(binwidth = 10) + facet_grid( SEX ~ .) + labs(x = "Non-Travel Marginal MET-hrs./week", colour = "Age") + coord_cartesian(xlim = c(0, 400))

```

```{r parameters, eval = TRUE, echo = FALSE}
parameters <- ddply(D, .(SEX, AGECAT), summarise,
             mean = mean(METs, na.rm=T),
             sd = sd(METs, na.rm=T)
             )

METmatrix <- rbind(matrix(0,nrow = 2, ncol = 2), matrix(parameters$mean, ncol = 2))

colnames(METmatrix) <- c(as.character(parameters$SEX[1]),as.character(rev(parameters$SEX)[1]))

METmatrix <- METmatrix[,c("male","female")]

METmatrix <- METmatrix/METmatrix[3,2]
METmatrix[2,] <- METmatrix[3,]
rownames(METmatrix) <- paste0("ageClass",1:8)
colnames(METmatrix) <- c("M","F")
METmatrix
```

## GBD Estimates by State

```{r stateBurden, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = 1/phi, echo = TRUE, warning = FALSE}

stateNameToAbbrev <- function( stateName ){
  stateAbbrevMatrix <- matrix(c("Alabama","AL","Alaska","AK","Arizona","AZ","Arkansas","AR","California","CA","Colorado","CO","Connecticut","CT","Delaware","DE","District of Columbia","DC","Florida","FL","Georgia","GA","Hawaii","HI","Idaho","ID","Illinois","IL","Indiana","IN","Iowa","IA","Kansas","KS","Kentucky","KY","Louisiana","LA","Maine","ME","Maryland","MD","Massachusetts","MA","Michigan","MI","Minnesota","MN","Mississippi","MS","Missouri","MO","Montana","MT","Nebraska","NE","Nevada","NV","New Hampshire","NH","New Jersey","NJ","New Mexico","NM","New York","NY","North Carolina","NC","North Dakota","ND","Ohio","OH","Oklahoma","OK","Oregon","OR","Pennsylvania","PA","Rhode Island","RI","South Carolina","SC","South Dakota","SD","Tennessee","TN","Texas","TX","Utah","UT","Vermont","VT","Virginia","VA","Washington","WA","West Virginia","WV","Wisconsin","WI","Wyoming","WY"), byrow = TRUE, ncol = 2)

  stateAbbrev <- stateAbbrevMatrix[,2]
  names(stateAbbrev) <- as.character(stateAbbrevMatrix[,1])
  return(stateAbbrev[stateName])
}

gbdParse <- function(gbd){
  gbdListTemp <- split(gbd,gbd$disease)
  gbdListTemp2 <- lapply(gbdListTemp,function(x) split(x,as.factor(x$sex)))
  gbdListTemp2 <- lapply(gbdListTemp2, function(x) list(M=x$M,F=x$F))
  return(gbdListTemp2)
}

gbdRDS <-  readRDS(file = "~/GHI/R/data/stateMetroBurdens2014.rds")
gbdRDS <- within(gbdRDS, state <- stateNameToAbbrev(state))

GBD <- bind_rows(
  gbdRDS %>%
  melt() %>%
  filter(disease %in% c("IHD", "HHD", "InflammatoryHD")) %>%
  group_by(state, sex, ageClass, variable) %>% summarise(value = sum(value)) %>%
  mutate(disease = "CVD"),
  gbdRDS %>%
  melt() %>%
  filter(disease %in% c("BreastCancer","ColonCancer","Dementia", "Diabetes", "Depression", "RTIs"))
)

GBD <- within(GBD, {
  variable <- ifelse(variable == "dproj","deaths", as.character(variable))
})

GBD <- with(GBD, data.frame(state, disease, sex, ageClass, burdenType = variable, value, stringsAsFactors = FALSE)) %>% arrange(state,disease,sex,ageClass,burdenType)

gbdByState <- split(GBD,GBD$state)
gbdByState <- lapply(gbdByState, function(x) x[,!names(x)=="state"])
gbdList <- lapply(gbdByState, gbdParse)


```



## Create List of ITHIM Objects


```{r ITHIMObjs, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = 1/phi, echo = TRUE, warning = FALSE}
stateVec <- names(listOfLists) #c("CA","NY","WI","MI","OH") #c("CA","TX","NY","FL","VA","NC","AZ")
stateVec <- stateVec[stateVec != "ND"]
stateVecOrdered <- stateVec #c("NY","CA","WI","MI","OH") #c("NC","TX","VA","FL","AZ","NY","CA")

upper <- 10; length <- 2; wd <- upper/length;

DALYsTotal <- data.frame()
ITHIMList <- list()
ITHIM.default <- createITHIM()

ITHIM.default <- update(ITHIM.default, list( cvNonTravel = 3, cv = 1.65, muNonTravel = 4, muNonTravelMatrix = METmatrix, quantiles = (1:99)/100 ) )

ITHIM.national <- update(ITHIM.default, list(muwt = muwtNational, muct = muctNational, Rwt = RwtNational, Rct = RctNational))

for (HHSTATE in stateVec){
    ITHIMList[[HHSTATE]] <- ITHIM.default
    ITHIMList[[HHSTATE]] <- update(ITHIM.default, list(muwt = muwtList[[HHSTATE]], muct = muctList[[HHSTATE]], Rwt = RwtList[[HHSTATE]], Rct = RwtList[[HHSTATE]], GBD = gbdList[[HHSTATE]]))
  }

for( muNonTravel in seq(0, upper, by = wd)){

  rm(DALYs)

  for (HHSTATE in stateVec){
    ITHIMList[[HHSTATE]] <- update(ITHIMList[[HHSTATE]], list(muNonTravel = muNonTravel))
  }

  ITHIM.national <- update(ITHIM.national, list(muNonTravel = muNonTravel))

  DALYs <- lapply(ITHIMList, deltaBurden, baseline = ITHIM.national)
  DALYs <- data.frame(State = names(DALYs), muNonTravel = muNonTravel, DALY = unlist(DALYs))
  DALYsTotal <- rbind(DALYsTotal, DALYs)
}

DALYsTotal <- within(DALYsTotal, {
  State <- factor(State, levels = stateVecOrdered)
})

p <- ggplot(DALYsTotal, aes(x = muNonTravel, y = DALY/1e3, colour = State))

p + stat_smooth( method = loess) + theme_bw() + scale_x_continuous(name="Mean Non-Travel METs (MET-hrs./week) (Referent Group)") + scale_y_continuous(name="Change in National DALYs (Thousands)") + coord_cartesian(xlim = c(0, upper))

p + stat_smooth( method = loess) + theme_bw() + scale_x_continuous(name="Mean Non-Travel METs (MET-hrs./week) (Referent Group)") + scale_y_continuous(name="Change in National DALYs (Thousands)") + coord_cartesian(xlim = c(0, upper)) + geom_point()

ITHIMList <- as(ITHIMList, "ITHIMList")
saveRDS(ITHIMList, file = "./data/ITHIMList.by.state.rds")

```

```{r statewiseGBD, eval = TRUE, dev=c('pdf', 'png'), fig.width = 2*fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = FALSE}
D <- do.call(rbind, mapply(function(df,state) data.frame(df, state = state), lapply(ITHIMList, getGBD), names(ITHIMList), SIMPLIFY = FALSE))
names(D) <- c("disease","sex","ageClass","type", "burden", "state")

D <- within(D, sex <- factor(sex, levels = c("F","M")))
D <- within(D, state <- factor(state, levels = c("WI","MI","OH","NY","CA")))

D <- subset(D, disease %in% c("BreastCancer","ColonCancer","Dementia","Depression","Diabetes", "CVD"))
D <- subset(D, as.character(state) %in% c("WI","MI","OH"))
D <- subset(D, type == "daly")

p <- ggplot(D, aes(x = ageClass, y = burden/1e3, fill = sex)) + geom_bar(stat= "identity", position = "dodge")
p + theme_bw() + scale_x_discrete(name="", labels = c("0-4","5-14","15-29","30-44","45-59","60-69","70-79","80+")) + scale_y_continuous(name="DALYs (thousands)") + theme(axis.text.x  = element_text(angle = 270, vjust = 0.5, size = 8)) + facet_grid( disease ~ state, scales = "free_y")
```

```{r rustBelt, eval = TRUE, dev=c('pdf', 'png'), fig.width = 2*fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = FALSE}

ITHIMList <- ITHIMList[names(ITHIMList) != "Natl."] # The national ITHIM obnject needs to have GBD updated.

ITHIMListScenario <- lapply(ITHIMList, function(ithim) update(ithim, list(muwt = ithim@parameters@muwt + 10*7)))

deltaDALYList <- mapply(deltaBurden, ITHIMList, ITHIMListScenario)
```

```{r rustBelt2, eval = TRUE, dev=c('pdf', 'png'), fig.width = 2*fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = FALSE}

cbPalette <- c("#0072B2", "#56B4E9", "#999999", "#E69F00", "#009E73", "#F0E442", "#D55E00", "#CC79A7")

D <- rbind(data.frame(getWalkTime(ITHIMList[["MI"]]),state = "MI"), data.frame(getWalkTime(ITHIMList[["WI"]]),state = "WI"), data.frame(getWalkTime(ITHIMList[["OH"]]),state = "OH"))

p <- ggplot(subset(D, ageClass != "ageClass1"), aes(x = ageClass, y = mean, fill = state)) + geom_bar(stat= "identity", position = "dodge")
p + theme_bw() + facet_grid( . ~ sex) + scale_x_discrete(name="", labels = c("5-14","15-29","30-44","45-59","60-69","70-79","80+")) + scale_y_continuous(name="Time Walking per Week (minutes)") + theme(axis.text.x  = element_text(angle = 90, vjust = 0.5, size = 8)) + scale_fill_manual(values=cbPalette[-3])

```

### Visualization of trip time matrices

```{r meanMatrices, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = FALSE}

ITHIMList <- c(ITHIMList, list("Natl." = ITHIM.national))

meanMatrix <- function(ITHIM, mode = "Walking"){
   if(mode == "Walking"){
      return(with(as(ITHIM@parameters,"list"), data.frame(ageClass = factor(1:8), mode = mode, Rwt*muwt)))
   }else if (mode == "Cycling"){
      return(with(as(ITHIM@parameters,"list"), data.frame(ageClass = factor(1:8), mode = mode, Rct*muct)))
   }else{
      message("error in meanMatrix function")
   }
}

meanMatrixListWalk <- lapply(ITHIMList, meanMatrix, mode = "Walking")
meanMatrixListCycle <- lapply(ITHIMList, meanMatrix, mode = "Cycling")

D <- melt(c(meanMatrixListWalk,meanMatrixListCycle))
names(D) <- c("ageClass", "mode", "Sex", "time", "State")

D <- within(D,{
  State <- factor(State, levels = c("NC","TX","VA","FL","AZ","NY","CA","Natl."))
  Sex <- factor(Sex, levels = c("F","M"))
})

p <- ggplot(subset(D,ageClass != 1), aes(x = ageClass, y = time, fill = Sex)) + geom_bar(stat= "identity", position = "dodge")
p + theme_bw() + scale_x_discrete(name="", labels = c("5-14","15-29","30-44","45-59","60-69","70-79","80+")) + scale_y_continuous(name="Travel Time per Week (minutes)") + facet_grid( mode ~ State, scales = "free_y") + theme(axis.text.x  = element_text(angle = 90, vjust = 0.5, size = 5))

```

```{r California, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = phi, warning = FALSE, message = FALSE, echo = FALSE}
ITHIM.national <- update(ITHIM.national, list(muNonTravel = 10))

#~~~~~~~~~~

ITHIM.CA <- ITHIMList[["CA"]]
ITHIM.CA <- update(ITHIM.CA, list(muNonTravel = 10))
foo1 <- ITHIM:::compareModels(ITHIM.national,ITHIM.CA)
foobar1 <- data.frame(cbind(melt(foo1$daly.delta),paste0("ageClass",1:8)),State = "CA")

foobar <- foobar1
names(foobar) <- c("delta.DALY","Sex","Disease","ageClass","State")

#~~~~~~~~~~

ITHIM.NY <- ITHIMList[["NY"]]
ITHIM.NY <- update(ITHIM.NY, list(muNonTravel = 10))
foo2 <- ITHIM:::compareModels(ITHIM.national,ITHIM.NY)
foobar2 <- data.frame(cbind(melt(foo2$daly.delta),paste0("ageClass",1:8)),State = "NY")
foobar <- rbind(foobar1,foobar2)
names(foobar) <- c("delta.DALY","Sex","Disease","ageClass","State")

foobar <- within(foobar, {
  Disease[Disease == "BreastCancer"] <- "Breast Cancer"
  Disease[Disease == "ColonCancer"] <- "Colon Cancer"
  Disease <- factor(Disease, levels = c("Breast Cancer", "Colon Cancer", "Dementia", "Depression", "Diabetes", "CVD"))
})

#~~~~~~~~~~

p <- ggplot( subset(foobar,ageClass != "ageClass1"), aes(ageClass,-delta.DALY/1e3, fill = State))

p + geom_bar(stat="identity", position = "dodge") +
theme(axis.title=element_blank()) +
facet_grid( Disease ~ Sex, scales = "free" ) +
scale_y_continuous(name="DALYs Averted Nationwide (Thousands)") +
scale_x_discrete(name="", labels = c("5-14","15-29","30-44","45-59","60-69","70-79","80+")) +
theme(axis.text.x  = element_text(angle=90, vjust=0.5, size=6)) +
scale_fill_manual(values=c("#CC6666", "#9999CC"))

```

```{r counts, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = phi, warning = FALSE, message = FALSE, echo = FALSE}
D <- melt(counts)
names(D) <- c("count","AgeClass","Sex", "State")
D <- within(D,{
  State <- factor(State, levels = c("NC","TX","VA","FL","AZ","NY","CA","Natl."))
  Sex <- factor(Sex, levels = c("F","M"))
})
p <- ggplot(subset(D,AgeClass != "00-04"), aes(AgeClass, count/1e3))
p + geom_bar(stat="identity", position = "dodge") + scale_x_discrete(name="", labels = c("5-14","15-29","30-44","45-59","60-69","70-79","80+")) + scale_y_continuous(name="Individuals Sampled (Thousands)") + facet_grid( State ~ .) + theme_bw() + coord_flip() # + theme(axis.text.x  = element_text(angle=90, vjust=0.5, size=6))
```


## Figure 1

```{r methodsPaper, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = FALSE}
ITHIM.default <- update(ITHIM.default, list(quantiles = (1:99)/100))

ITHIM.national <- ITHIM.default

RwtNational[1,] <- c(1e-6,1e-6)
RctNational[1,] <- c(1e-6,1e-6)

ITHIM.national <- update(ITHIM.national, list(muwt = muwtNational, muct = muctNational,Rwt = RwtNational,Rct = RctNational))

saveRDS(ITHIM.national, file = "./data/ITHIM.national.rds")

ITHIM.scenario <- ITHIM.national
ITHIM.national.quints <- update(ITHIM.national, list(quantiles = seq(1,9,by=2)/10))
ITHIM.scenario.quints <- update(ITHIM.scenario, list(quantiles = seq(1,9,by=2)/10))

pWalk <- ITHIM.national@means$pWalk[3,2]

DALYs <- c(); DALYs.quints <- c();
atVec <- seq(45, 120, length.out = 3)
muNonTravelVec <- c(1, 10, 25)
DTotal <- data.frame()

for(at in atVec ){  # minutes active transport/week
  for( muNonTravel in muNonTravelVec ){

    ITHIM.scenario <- update(ITHIM.scenario, list(muwt = at*pWalk, muct = at*(1-pWalk), muNonTravel = muNonTravel))

    ITHIM.scenario.quints <- update(ITHIM.scenario.quints, list(muwt = at*pWalk, muct = at*(1-pWalk), muNonTravel = muNonTravel))


    ITHIM.national <- update(ITHIM.national, list(muNonTravel = muNonTravel))

    DALYs <- deltaBurden(ITHIM.national, ITHIM.scenario)
    DALYs.quints <- deltaBurden(ITHIM.national.quints, ITHIM.scenario.quints)

    D <- data.frame(quants = c("percentiles","quintiles"), DALYs = c(DALYs,DALYs.quints),at = at, muNonTravel = muNonTravel)

    DTotal <- rbind(D,DTotal)

  }
}

DTotal <- within(DTotal, muNonTravel <- factor(muNonTravel, levels = as.character(muNonTravelVec), labels = c("low","medium","high")))
DTotal <- subset(DTotal, quants == "percentiles")


p <- ggplot(DTotal, aes(x = at, y = -DALYs/1e3, colour = muNonTravel))
p + geom_line() + geom_point() + theme_bw() + scale_y_continuous(name="DALYs Averted Nationwide (Thousands)") + scale_x_continuous(name="Active Transport (minutes/week) (Referent Group)")  + scale_colour_discrete(name="Baseline Activity") #+ theme(axis.text.x  = element_text(angle = 90, vjust = 0.5, size = 8))

```


```{r displayMeans, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = phi, warning = FALSE, message = FALSE, echo = FALSE}

ITHIM.national <- update(ITHIM.national, list(muNonTravel = 10))

D <- rbind(getWalkTime(ITHIM.national),getCycleTime(ITHIM.national),getNonTravelMETs(ITHIM.national))
D <- within(D, sex <- factor(sex, levels = c("F","M")))

p <- ggplot(D, aes(x = ageClass, y = mean, fill = sex)) + geom_bar(stat= "identity", position = "dodge")
p + theme_bw() + scale_x_discrete(name="", labels = c("0-4","5-14","15-29","30-44","45-59","60-69","70-79","80+")) + scale_y_continuous(name="") + theme(axis.text.x  = element_text(angle = 90, vjust = 0.5, size = 8)) + facet_grid( type ~ ., scales = "free")
```

## Figure 3

```{r displayGBD, eval = TRUE, dev=c('pdf', 'png'), fig.width = 1.2*fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = FALSE}

D <- melt(ITHIM.national@parameters@GBD)

D <- getGBD(ITHIM.national)

names(D) <- c("disease","sex","ageClass","type","burden")
D <- within(D, sex <- factor(sex, levels = c("F","M")))

p <- ggplot(subset(D, disease %in% c("BreastCancer","ColonCancer","Dementia","Depression","Diabetes", "CVD") & type == "daly"), aes(x = ageClass, y = burden/1e3, fill = sex)) + geom_bar(stat= "identity", position = "dodge")

p + theme_bw() + scale_x_discrete(name="", labels = c("0-4","5-14","15-29","30-44","45-59","60-69","70-79","80+")) + scale_y_continuous(name="DALYs Nationwide (thousands)") + theme(axis.text.x  = element_text(angle = 270, vjust = 0.5, size = 8)) + facet_grid( . ~ disease, scales = "free_y")
```



```{r doseresponse, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = 1/phi, echo = TRUE, warning = FALSE}
RR1vec <- unique(unlist(ITHIM:::createActiveTransportRRs()))
lapply(ITHIM:::createActiveTransportRRs(),function(x) lapply(x, function(x) unique(c(x))))
#~~~~~~~~~~~~~~~~~~~~~~~
# Manual bull$%#@!
#~~~~~~~~~~~~~~~~~~~~~~~
RR1vec <- RR1vec[RR1vec != 1]
names(RR1vec) <- c("BreastCancer","ColonCancer.M","ColonCancer.F", "CVD", "Dementia", "Depression.young", "Depression.old", "Diabetes")

RRx <- function(x, RR1, k) exp(log(RR1)*x^k)
x <- seq(0,25,0.1)
RRmat <- outer(x, RR1vec, RRx, k = 0.5)
rownames(RRmat) <- x
D <- melt(RRmat)
names(D) <- c("x","disease","RR")

p <- ggplot(D, aes(x = x, y = RR, colour = disease))
p + geom_line()  + theme_bw() + scale_y_continuous(name="Relative Risk") + scale_x_continuous(name="Physical Activity (MET-hrs./week)")
```

## Wisconsin & Michigan


```{r wimi, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = 1/phi, echo = TRUE, warning = FALSE}

ITHIM.NY <- ITHIMList[["NY"]]
ITHIM.CA <- ITHIMList[["CA"]]
ITHIM.MI <- ITHIMList[["MI"]]
ITHIM.WI <- ITHIMList[["WI"]]
ITHIM.WI <- ITHIMList[["OH"]]

prop <- 1/50
state1Vec <- c("MI","WI","OH")
state2Vec <- c("NY","CA")

foobar <- data.frame()

for( state1 in state1Vec ){
    for( state2 in state2Vec ){
        foo <- data.frame(lapply(ITHIM:::compareModels(ITHIMList[[state1]],ITHIMList[[state2]])$daly.delta, function(x) sum(x$M + x$F)*prop), baseline = state1, scenario = state2)
        foobar <- rbind(foobar,foo)
    }
}

D <- melt(foobar)
names(D) <- c("baseline","scenario","disease","DALYs")

p <- ggplot(D, aes(x = disease, y = -DALYs/1e3, fill = scenario)) + geom_bar(stat= "identity", position = "dodge")
p + theme_bw() + scale_y_continuous(name="DALYs Averted (thousands)") + facet_grid( . ~ baseline) + theme(axis.text.x  = element_text(angle = 90, vjust = 0.5, size = 8)) + theme(legend.title=element_blank()) + scale_x_discrete(name="Disease")

#+ theme(axis.text.x  = element_text(angle = 270, vjust = 0.5, size = 8)) + facet_grid( . ~ disease, scales = "free_y")
```

```{r sessionInfo, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = 1/phi, echo = TRUE, warning = FALSE}
sessionInfo()
```

```{r rustBeltOld, eval = FALSE, dev=c('pdf', 'png'), fig.width = 2*fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = FALSE}
## getDALY <- function( ITHIM ){
## foo <- data.frame(lapply(ITHIM@parameters@GBD, function(x) x$M$daly + x$F$daly))
## sum(foo[,names(foo) %in% c("BreastCancer","ColonCancer","Dementia","Depression","Diabetes", "CVD")])
## }

## burdenList <- lapply(ITHIMList, getDALY)
## foo <- data.frame(daly = unlist(burdenList), delta = deltaDALYList)
## foo <- within(foo, {
##   daly <- daly + delta
##   delta <- -delta
##   state <- names(burdenList)
## })

## foo <- subset(foo, state %in% c("MI","OH"))

## D <- melt(foo)

## cbPalette <- c("#0072B2", "#56B4E9", "#999999", "#E69F00", "#009E73", "#F0E442", "#D55E00", "#CC79A7")

## p <- ggplot(D, aes(state, value/1e3, fill = variable))
## p + geom_bar(stat= "identity") + scale_x_discrete(name="") + scale_y_continuous(name="Thousands of DALYs") + guides(fill=FALSE) + scale_fill_manual(values=cbPalette) + theme(axis.text.y  = element_text(size = 16)) + theme(axis.text.x  = element_text(size = 16), axis.title.x  = element_text(size = 16)) + coord_flip()
```
