# Travel Survey Exploratory Analysis

```{r libs, eval = TRUE, echo = FALSE, results = "hide", warning = FALSE, error = FALSE, message = FALSE}
rm(list=ls())
library("tidyverse")
library("ITHIM")
library("TravelSurvey")
```

```{r loadITHIM, message = FALSE, eval = TRUE, warning = FALSE, error = TRUE, echo = FALSE}
fig.width <- 24 # inches
phi <- (1+sqrt(5))/2 # the golden ratio ;)
```

## Mode share of walk/bike by MSA

```{r plot1, eval = TRUE, fig.width = fig.width, echo = FALSE, fig.asp = 1/phi}
total <- NHTS.df %>% group_by(location) %>% summarise(mean = mean(duration), total = sum(duration), sdTotal = sd(duration), nTotal = n())

byMode <- NHTS.df %>% group_by(location, mode) %>% summarise(byMode = mean(duration), sdMode = sd(duration), nMode=n() )
NHTS.table1 <- dplyr::full_join(byMode, total, by = "location") %>% mutate(propMode = byMode/total) %>% dplyr::filter(mode %in% c("walk","cycle")) %>% mutate(ciModeLeft = byMode - 1.96*sdMode/sqrt(nMode), ciModeRight = byMode + 1.96*sdMode/sqrt(nMode))

p <- ggplot(data = NHTS.table1, aes(x = location, y = propMode, fill = mode))
p + geom_bar(stat="identity") + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1))

NHTS.table2 <- NHTS.table1 %>% select(location, mode, ciModeLeft, ciModeRight) %>% gather(ciMode, value, 3:4)
NHTS.table2 <- within(NHTS.table2, {
    location <- factor(location, levels=unique(location[order(value)]))
    })

p <- ggplot(NHTS.table2, aes(x = location, y = value, colour = mode))
p + geom_line(aes(group = ciMode)) + facet_grid(mode ~ . ) + theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

## Distribution of Trip Duration by MSA

```{r plot2, eval = TRUE, fig.width = fig.width, echo = FALSE, fig.asp = 1/phi}
p <- ggplot(subset(NHTS.df,!is.na(mode)), aes(x = location, y = duration, fill = location))
p + geom_boxplot(outlier.shape = NA) + ylim(0,60) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
p + geom_violin(scale = "width" ) + ylim(0,60) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

### Distribution of Trip Duration for Portland, OR MSA (6442)

```{r plot3, eval = TRUE, echo = FALSE, fig.width = fig.width, fig.asp = 1/phi}
p <- ggplot(subset(NHTS.df,!is.na(mode) & location == "6442"), aes(x = mode, y = duration, fill = mode))
p + geom_boxplot(outlier.shape = NA) + ylim(0,60) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
p + geom_violin(scale = "width", adjust = 4 ) + ylim(0,60) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r means, eval = TRUE, echo = FALSE, fig.width = fig.width, fig.asp = 1/phi}
meanDuration <- NHTS.df %>% group_by(location,sex,age,mode) %>% summarise(meanDuration = mean(duration))

%>% complete(nesting(location,sex,age,mode))

```


```{r msa, eval = TRUE, fig.width = fig.width, echo = FALSE}
#foo <- read.csv(file ="./../data/cbsatocountycrosswalk.csv", colClasses = "character")
foo <- read.csv(file = "~/GHI/data/MSA.csv", colClasses = c("character","character"))
names(foo) <- c("msa","msaname")
#foo <- unique(foo[,c("msa","msaname")])
msa <- foo$msa
msaname <- foo$msaname
names(msaname) <- msa

```
