## ITHIM Tutorial

### Installing the package

```{r figwidth, eval = TRUE,  warning = FALSE, message = FALSE, echo = FALSE}
fig.width <- 6
phi <- (1+sqrt(5))/2 # the golden ratio ;)
```

First load the package from Github.  To do this you need the package
devtools.

```{r, libs, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = TRUE}
options(repos='http://cran.rstudio.com/')
install.packages("devtools")
```

Now load the package and install ITHIM.

```{r libs2, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = TRUE}
library("devtools")
#install_github(repo = "syounkin/ITHIM", ref = "devel")
install("~/ITHIM/")
library("ITHIM")
```


### Create default ITHIM object

```{r create, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = TRUE}
ITHIM.baseline <- createITHIM()
```

### ITHIM Methods


#### getMeans

```{r methods3, eval = TRUE, dev=c('png'), fig.width = fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = TRUE}
getMeans(ITHIM.baseline)
```

#### update

```{r update, eval = TRUE, dev=c('png'), fig.width = fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = TRUE}
ITHIM.scenario <- update(ITHIM.baseline, list(muwt = 2*getMeans(ITHIM.baseline)$walk))
```

#### compareModels

```{r compareModels, eval = TRUE, dev=c('png'), fig.width = fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = TRUE}
CRA.list <- compareModels(ITHIM.baseline,ITHIM.scenario)
```

#### Plot

```{r methods2, eval = FALSE, dev=c('png'), fig.width = fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = TRUE}
plot(ITHIM.baseline)
```

#### getMethodsITHIM

```{r getMethods, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = TRUE}
getMethodsITHIM()
```

### The _ParameterSet_ Object

Each ITHIM object contains a ParameterSet object.

```{r pSet, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = TRUE}
paramSet.baseline <- getParameterSet(ITHIM.baseline)
paramSet.scenario <- getParameterSet(ITHIM.scenario)
```

```{r class, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = TRUE}
paramSet.baseline
```

```{r class2, eval = TRUE, dev=c('pdf', 'png'), fig.width = fig.width, fig.asp = 1/phi, warning = FALSE, message = FALSE, echo = TRUE}
paramSet.scenario
```

